// services/web/src/routes/dashboard/settings/+page.svelte
<script lang="ts">
	let user = {
		full_name: 'John Doe',
		email: 'john.doe@example.com'
	};

	let business = {
		business_logo:
			'https://eswpcd25uod.exactdn.com/blog/wp-content/uploads/2017/05/01-1024x1024.jpg?strip=all&lossy=1&ssl=1',
		business_name: 'Freelyce',
		business_email: 'freelyce@proton.me',
		business_address:
			'Jl. Jend. Sudirman No. 52-53, Jakarta Selatan, Indonesia',
		business_telepon: '081234567890'
	};

	let logoPreview: string | null = business.business_logo;
	let logoFile: File | ArrayBuffer | null = null;

	let currentPassword = '';
	let newPassword = '';
	let confirmPassword = '';

	function handleLogoChange(event: Event) {
		const input = event.target as HTMLInputElement;
		if (input.files && input.files[0]) {
			logoFile = input.files[0];
			const reader = new FileReader();
			reader.onload = (e) => {
				const result = e.target?.result;
				logoPreview = typeof result === 'string' ? result : null;
			};
			reader.readAsDataURL(logoFile);
		}
	}

	function handleProfileSubmit() {
		console.log('Menyimpan data profil:', { user, business });
		if (logoFile && logoFile instanceof File) {
			console.log('Mengunggah logo baru:', logoFile.name);
		}
		alert('Data profil berhasil disimpan!');
	}

	function handlePasswordChange() {
		if (newPassword !== confirmPassword) {
			alert('Konfirmasi kata sandi baru tidak cocok!');
			return;
		}
		if (!newPassword || newPassword.length < 8) {
			alert('Kata sandi baru minimal harus 8 karakter.');
			return;
		}

		console.log('Mengubah kata sandi...', { currentPassword, newPassword });
		alert('Kata sandi berhasil diubah!');
	}
</script>

<div class="mx-auto">
	<h1 class="text-text-primary mb-8 text-3xl font-bold">Pengaturan Profil</h1>
	<form
		on:submit|preventDefault={handleProfileSubmit}
		class="mb-8 bg-white"
	>
		<h2
			class="text-text-primary mb-6 border-b border-slate-200 pb-4 text-xl font-semibold"
		>
			Informasi Bisnis
		</h2>

		<div class="space-y-6">
			<div class="flex items-center space-x-6">
				{#if logoPreview}
					<img
						src={logoPreview}
						alt="Logo Bisnis"
						class="h-24 w-24 rounded-full object-cover"
					/>
				{/if}
				<div>
					<label
						for="logo-upload"
						class="cursor-pointer rounded bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow transition-all duration-200 hover:scale-105 hover:shadow-lg"
					>
						Ubah Logo
					</label>
					<input
						id="logo-upload"
						name="logo-upload"
						type="file"
						class="sr-only"
						accept="image/*"
						on:change={handleLogoChange}
					/>
					<p class="text-text-secondary mt-2 text-xs">
						PNG, JPG, GIF hingga 2MB.
					</p>
				</div>
			</div>
			<div class="grid grid-cols-1 gap-6 md:grid-cols-2">
				<div>
					<label
						for="business_name"
						class="text-text-primary mb-1 block text-sm font-medium"
						>Nama Bisnis</label
					>
					<input
						type="text"
						id="business_name"
						bind:value={business.business_name}
						class="focus:border-primary focus:ring-primary w-full rounded border border-gray-300 px-4 py-2 shadow-sm"
					/>
				</div>
				<div>
					<label
						for="business_email"
						class="text-text-primary mb-1 block text-sm font-medium"
						>Email Bisnis</label
					>
					<input
						type="email"
						id="business_email"
						bind:value={business.business_email}
						class="focus:border-primary focus:ring-primary w-full rounded border border-gray-300 px-4 py-2 shadow-sm"
					/>
				</div>
				<div class="md:col-span-2">
					<label
						for="business_telepon"
						class="text-text-primary mb-1 block text-sm font-medium"
						>Nomor Telepon</label
					>
					<input
						type="tel"
						id="business_telepon"
						bind:value={business.business_telepon}
						class="focus:border-primary focus:ring-primary w-full rounded border border-gray-300 px-4 py-2 shadow-sm"
					/>
				</div>
				<div class="md:col-span-2">
					<label
						for="business_address"
						class="text-text-primary mb-1 block text-sm font-medium"
						>Alamat Bisnis</label
					>
					<textarea
						id="business_address"
						rows="3"
						bind:value={business.business_address}
						class="focus:border-primary focus:ring-primary w-full rounded border border-gray-300 px-4 py-2 shadow-sm"
					></textarea>
				</div>
			</div>
		</div>
		<div class="mt-8 pt-6">
			<h2
				class="text-text-primary mb-6 border-b border-slate-200 pb-4 text-xl font-semibold"
			>
				Informasi Personal
			</h2>
			<div class="grid grid-cols-1 gap-6 md:grid-cols-2">
				<div>
					<label
						for="full_name"
						class="text-text-primary mb-1 block text-sm font-medium"
						>Nama Lengkap</label
					>
					<input
						type="text"
						id="full_name"
						bind:value={user.full_name}
						class="focus:border-primary focus:ring-primary w-full rounded border border-gray-300 px-4 py-2 shadow-sm"
					/>
				</div>
				<div>
					<label
						for="email"
						class="text-text-primary mb-1 block text-sm font-medium"
						>Email Akun</label
					>
					<input
						type="email"
						id="email"
						bind:value={user.email}
						class="focus:border-primary focus:ring-primary w-full rounded border border-gray-300 px-4 py-2 shadow-sm"
					/>
				</div>
			</div>
		</div>
		<div class="mt-8">
			<button
				type="submit"
				class="hover:bg-primary bg-primary cursor-pointer rounded px-5 py-2.5 text-sm font-semibold text-white shadow transition-all duration-200 hover:scale-105 hover:shadow-lg"
			>
				Simpan Perubahan
			</button>
		</div>
	</form>
	<form
		on:submit|preventDefault={handlePasswordChange}
		class="mt-8 max-w-4xl bg-white pt-6"
	>
		<h2
			class="text-text-primary mb-6 border-b border-slate-200 pb-4 text-xl font-semibold"
		>
			Keamanan Kata Sandi
		</h2>
		<div class="space-y-4">
			<div>
				<label
					for="current_password"
					class="text-text-primary mb-1 block text-sm font-medium"
					>Kata Sandi Saat Ini</label
				>
				<input
					type="password"
					id="current_password"
					bind:value={currentPassword}
					class="focus:border-primary focus:ring-primary w-full rounded border border-gray-300 px-4 py-2 shadow-sm"
				/>
			</div>
			<div>
				<label
					for="new_password"
					class="text-text-primary mb-1 block text-sm font-medium"
					>Kata Sandi Baru</label
				>
				<input
					type="password"
					id="new_password"
					bind:value={newPassword}
					class="focus:border-primary focus:ring-primary w-full rounded border border-gray-300 px-4 py-2 shadow-sm"
				/>
			</div>
			<div>
				<label
					for="confirm_password"
					class="text-text-primary mb-1 block text-sm font-medium"
					>Konfirmasi Kata Sandi Baru</label
				>
				<input
					type="password"
					id="confirm_password"
					bind:value={confirmPassword}
					class="focus:border-primary focus:ring-primary w-full rounded border border-gray-300 px-4 py-2 shadow-sm"
				/>
			</div>
		</div>
		<div class="mt-6 flex justify-start">
			<button
				type="submit"
				class="bg-primary cursor-pointer rounded px-5 py-2.5 text-sm font-semibold text-white shadow transition-all duration-200 hover:scale-105 hover:shadow-lg"
			>
				Ubah Kata Sandi
			</button>
		</div>
	</form>
</div>

// app/(main)/settings/page.tsx
"use client";

import {
  Settings as SettingsIcon,
  User,
  Building,
  Shield,
  ArrowLeft,
} from "lucide-react";
import { useRouter } from "next/navigation";
import { Button } from "@/packages/shadcn/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/packages/shadcn/ui/card";
import { Label } from "@radix-ui/react-label";
import { Input } from "@/packages/shadcn/ui/input";
import { Textarea } from "@/packages/shadcn/ui/textarea";
import { useState, useEffect } from "react";

export default function Settings() {
  const router = useRouter();
  const [password, setPassword] = useState({
    old_password: "",
    new_password: "",
    confirm_password: "",
  });
  const [bussiness, setBussiness] = useState({
    business_name: "",
    business_email: "",
    business_address: "",
    phone: "",
  });
  const [profile, setProfile] = useState({
    name: "",
    email: "",
  });

  useEffect(() => {
    async function fetchDefaults() {
      try {
        const res = await fetch("/api/features/user/me", {
          method: "GET",
          credentials: "include",
        });
        const data = await res.json();

        setProfile({
          name: data.user.name || "",
          email: data.user.email || "",
        });
        setBussiness({
          business_name: data.user.business_name || "",
          business_email: data.user.business_email || "",
          business_address: data.user.business_address || "",
          phone: data.user.phone || "",
        });
      } catch (err) {
        console.error("Gagal mengambil data default:", err);
      }
    }

    fetchDefaults();
  }, []);

  const handleUpdateProfile = async () => {
    try {
      const res = await fetch("/api/features/user/update-profile", {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(profile),
        credentials: "include",
      });
      await res.json();
      alert("Profil berhasil diperbarui!");
    } catch (err) {
      console.error(err);
      alert("Gagal memperbarui profil");
    }
  };

  const handleUpdateBusiness = async () => {
    try {
      const res = await fetch("/api/features/user/update-profile", {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(bussiness),
        credentials: "include",
      });
      await res.json();
      alert("Bisnis berhasil diperbarui!");
    } catch (err) {
      console.error(err);
      alert("Gagal memperbarui bisnis");
    }
  };

  const handleChangePassword = async () => {
    if (password.new_password !== password.confirm_password) {
      alert("Password baru dan konfirmasi tidak cocok!");
      return;
    }

    try {
      await fetch("/api/features/user/change-password", {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          old_password: password.old_password,
          new_password: password.new_password,
        }),
        credentials: "include",
      });
      alert("Password berhasil diubah!");
      setPassword({ old_password: "", new_password: "", confirm_password: "" });
    } catch (err) {
      console.error(err);
      alert("Gagal mengubah password");
    }
  };

  return (
    <div className="min-h-screen bg-background">
      <main className="container mx-auto max-w-7xl py-4 px-4 sm:px-6 lg:px-8">
        <Button
          className="bg-white"
          size="sm"
          onClick={() => router.push("/dashboard")}
        >
          <ArrowLeft className="h-4 w-4 mr-2" />
          Kembali
        </Button>
        <div className="my-4 flex items-center space-x-3">
          <div className="p-2 bg-primary rounded-lg">
            <SettingsIcon className="h-6 w-6 text-primary-foreground" />
          </div>
          <div>
            <h1 className="text-2xl font-bold text-foreground">Pengaturan</h1>
            <p className="text-muted-foreground">
              Kelola pengaturan aplikasi Anda
            </p>
          </div>
        </div>
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          <div className="lg:col-span-2 lg:row-span-2">
            <Card className="bg-white h-full">
              <CardHeader>
                <CardTitle className="flex items-center space-x-2">
                  <Building className="h-5 w-5" />
                  <span>Bisnis</span>
                </CardTitle>
                <CardDescription>
                  Informasi bisnis untuk invoice
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="companyName">Nama Bisnis</Label>
                    <Input
                      id="companyName"
                      value={bussiness.business_name}
                      onChange={(e) =>
                        setBussiness({
                          ...bussiness,
                          business_name: e.target.value,
                        })
                      }
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="companyEmail">Email Bisnis</Label>
                    <Input
                      id="companyEmail"
                      type="email"
                      value={bussiness.business_email}
                      onChange={(e) =>
                        setBussiness({
                          ...bussiness,
                          business_email: e.target.value,
                        })
                      }
                    />
                  </div>
                </div>
                <div className="space-y-2">
                  <Label htmlFor="phone">Nomor Telepon</Label>
                  <Input
                    id="phone"
                    value={bussiness.phone}
                    onChange={(e) =>
                      setBussiness({ ...bussiness, phone: e.target.value })
                    }
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="companyAddress">Alamat</Label>
                  <Textarea
                    id="companyAddress"
                    value={bussiness.business_address}
                    onChange={(e) =>
                      setBussiness({
                        ...bussiness,
                        business_address: e.target.value,
                      })
                    }
                    className="resize-none min-h-[120px]"
                  />
                </div>
                <Button className="w-full" onClick={handleUpdateBusiness}>
                  Simpan
                </Button>
              </CardContent>
            </Card>
          </div>
          <div className="lg:col-span-1">
            <Card className="bg-white">
              <CardHeader>
                <CardTitle className="flex items-center space-x-2">
                  <User className="h-5 w-5" />
                  <span>Profil Pengguna</span>
                </CardTitle>
                <CardDescription>
                  Kelola informasi profil dan preferensi akun Anda
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-2">
                  <Label htmlFor="name">Full Name</Label>
                  <Input
                    id="name"
                    value={profile.name}
                    onChange={(e) =>
                      setProfile({ ...profile, name: e.target.value })
                    }
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="email">Email</Label>
                  <Input
                    id="email"
                    type="email"
                    value={profile.email}
                    disabled
                  />
                </div>
                <Button className="w-full" onClick={handleUpdateProfile}>
                  Simpan
                </Button>
              </CardContent>
            </Card>
          </div>
          <div className="lg:col-span-1">
            <Card className="bg-white">
              <CardHeader>
                <CardTitle className="flex items-center space-x-2">
                  <Shield className="h-5 w-5" />
                  <span>Keamanan</span>
                </CardTitle>
                <CardDescription>Pengaturan keamanan password</CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-2">
                  <Label htmlFor="currentPassword">Password Saat Ini</Label>
                  <Input
                    id="currentPassword"
                    type="password"
                    value={password.old_password}
                    onChange={(e) =>
                      setPassword({ ...password, old_password: e.target.value })
                    }
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="newPassword">Password Baru</Label>
                  <Input
                    id="newPassword"
                    type="password"
                    value={password.new_password}
                    onChange={(e) =>
                      setPassword({ ...password, new_password: e.target.value })
                    }
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="confirmPassword">
                    Konfirmasi Password Baru
                  </Label>
                  <Input
                    id="confirmPassword"
                    type="password"
                    value={password.confirm_password}
                    onChange={(e) =>
                      setPassword({
                        ...password,
                        confirm_password: e.target.value,
                      })
                    }
                  />
                </div>
                <Button className="w-full" onClick={handleChangePassword}>
                  Ubah Password
                </Button>
              </CardContent>
            </Card>
          </div>
        </div>
      </main>
    </div>
  );
}
