// app/(public)/components/navbar.tsx
"use client";

import Image from "next/image";
import Link from "next/link";
import { useState } from "react";

export default function Navbar() {
  const [isMenuOpen, setIsMenuOpen] = useState(false);

  const toggleMenu = () => {
    setIsMenuOpen(!isMenuOpen);
  };

  return (
    <>
      <nav className="w-full border-b-2 bg-white px-4 sm:px-6 md:px-10 lg:px-20 py-3 flex items-center justify-between sticky top-0 z-50">
        <Link href="/" className="flex items-center gap-2">
          <Image
            src="/banner-light.png"
            alt="logo"
            width="120"
            height="47"
            className="sm:w-[130px] md:w-[140px] lg:w-[150px]"
          />
        </Link>
        <div className="hidden lg:flex items-center gap-6">
          <Link
            href="#"
            className="font-medium hover:border-b-2 border-[#14BA85]"
          >
            About
          </Link>
          <Link
            href="#"
            className="font-medium hover:border-b-2 border-[#14BA85]"
          >
            Pricing
          </Link>
          <Link
            href="#"
            className="font-medium hover:border-b-2 border-[#14BA85]"
          >
            Blog
          </Link>
          <Link
            href="/auth/sign-in"
            className="bg-[#14BA85] border-2 border-black rounded-lg px-4 py-2 font-semibold shadow-[3px_3px_0px_black] hover:translate-x-[2px] hover:translate-y-[2px] hover:shadow-none transition"
          >
            Sign In
          </Link>
        </div>
        <div className="lg:hidden">
          <button
            onClick={toggleMenu}
            className="p-2 rounded-md hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200"
            aria-label="Toggle menu"
          >
            <div className="w-6 h-6 flex flex-col justify-center items-center">
              <span
                className={`bg-black block transition-all duration-300 ease-out h-0.5 w-6 rounded-sm ${
                  isMenuOpen ? "rotate-45 translate-y-1" : "-translate-y-0.5"
                }`}
              ></span>
              <span
                className={`bg-black block transition-all duration-300 ease-out h-0.5 w-6 rounded-sm my-0.5 ${
                  isMenuOpen ? "opacity-0" : "opacity-100"
                }`}
              ></span>
              <span
                className={`bg-black block transition-all duration-300 ease-out h-0.5 w-6 rounded-sm ${
                  isMenuOpen ? "-rotate-45 -translate-y-1" : "translate-y-0.5"
                }`}
              ></span>
            </div>
          </button>
        </div>
      </nav>
      {isMenuOpen && (
        <div className="lg:hidden fixed inset-0 z-50">
          <div className="fixed inset-0 bg-white">
            <div className="flex items-center justify-between px-4 py-3 border-b-2">
              <div className="flex items-center gap-2">
                <Image
                  src="/banner-light.png"
                  alt="logo"
                  width="120"
                  height="120"
                />
              </div>
              <button
                onClick={() => setIsMenuOpen(false)}
                className="p-2 hover:bg-gray-100 rounded-md transition-colors"
                aria-label="Close menu"
              >
                <svg
                  className="w-6 h-6"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M6 18L18 6M6 6l12 12"
                  />
                </svg>
              </button>
            </div>
            <div className="px-4 py-6">
              <div className="space-y-0">
                <Link
                  href="#"
                  className="block text-lg font-medium py-4 border-b border-gray-200 hover:bg-gray-50 transition-colors -mx-4 px-4"
                  onClick={() => setIsMenuOpen(false)}
                >
                  About
                </Link>
                <Link
                  href="#"
                  className="block text-lg font-medium py-4 border-b border-gray-200 hover:bg-gray-50 transition-colors -mx-4 px-4"
                  onClick={() => setIsMenuOpen(false)}
                >
                  Pricing
                </Link>
                <Link
                  href="#"
                  className="block text-lg font-medium py-4 border-b border-gray-200 hover:bg-gray-50 transition-colors -mx-4 px-4"
                  onClick={() => setIsMenuOpen(false)}
                >
                  Blog
                </Link>
                <div className="pt-6">
                  <Link
                    href="/auth/sign-in"
                    className="block w-full bg-[#14BA85] border-2 border-black rounded-xl px-6 py-3 font-semibold shadow-[3px_3px_0px_black] hover:translate-x-[2px] hover:translate-y-[2px] hover:shadow-none transition text-center"
                    onClick={() => setIsMenuOpen(false)}
                  >
                    Sign In
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </>
  );
}

// services/web/src/lib/components/core/navbar.svelte
<script lang="ts">
	import { fade } from 'svelte/transition';
	import { onMount, onDestroy } from 'svelte';
	import { Menu, X } from 'lucide-svelte';
	import logo from '$lib/assets/logo.png';

	let mobileMenuOpen = false;

	const toggleMobileMenu = () => {
		mobileMenuOpen = !mobileMenuOpen;
	};

	let showTicker = true;

	const tickerMessages = [
		'Buat Invoice Profesional dalam Waktu Kurang dari 3 Menit',
		'Hemat Waktu Administrasi, Fokus pada Karya Anda',
		'Dirancang untuk Freelancer, Pekerja Mandiri dan pelaku bisnis',
		'Cobalah Memulai dengan Gratis'
	];

	const doubledTickerMessages = [...tickerMessages, ...tickerMessages];

	const navLinks = [
		{ href: '#features', text: 'Features' },
		{ href: '#pricing', text: 'Pricing' },
		{ href: '#about', text: 'About' },
		{ href: '#contact', text: 'Contact' },
		{ href: '/blog', text: 'Blog' }
	];

	onMount(() => {
		const handleScroll = () => {
			showTicker = window.scrollY <= 20;
		};

		handleScroll();

		window.addEventListener('scroll', handleScroll);

		onDestroy(() => {
			window.removeEventListener('scroll', handleScroll);
		});
	});
</script>

<nav class="fixed top-0 z-50 w-full bg-white shadow-md backdrop-blur-sm">
	{#if showTicker}
		<div
			class="overflow-hidden bg-primary py-1.5 text-sm whitespace-nowrap text-white transition-all duration-300"
			transition:fade
		>
			<div class="news-ticker">
				{#each doubledTickerMessages as message}
					<span class="mx-8">{message}</span>
				{/each}
			</div>
		</div>
	{/if}

	<div class="mx-auto max-w-7xl px-6 pt-4 pb-2">
		<div class="flex items-center justify-between md:mx-0">
			<div class="flex items-center space-x-3">
				<a
					href="/"
					class="text-2xl text-text-primary md:text-4xl"
				>
					<img
						class="h-16 w-full md:h-[100px]"
						src={logo}
						alt="logo"
					/>
				</a>
			</div>

			<div class="hidden items-center space-x-8 md:flex">
				<a
					href="/auth/sign-in"
					class="hover-underline font-medium text-text-primary"
				>
					Sign-in
				</a>
				<a
					href="/auth/sign-up"
					class="cursor-pointer rounded bg-primary px-6 py-2 text-lg font-medium text-white transition-colors hover:opacity-80"
				>
					Get Started
				</a>
			</div>

			<button
				class="md:hidden"
				on:click={toggleMobileMenu}
				aria-label="button"
			>
				{#if mobileMenuOpen}
					<X class="h-6 w-6 text-text-primary" />
				{:else}
					<Menu class="h-6 w-6 text-text-primary" />
				{/if}
			</button>
		</div>
	</div>

	<div class="mx-auto hidden px-6 pb-2 md:block">
		<div
			class="mx-auto flex max-w-7xl items-center space-x-8 px-6 pt-1.5 text-sm text-text-primary"
		>
			{#each navLinks as link}
				<a
					href={link.href}
					class="hover-underline">{link.text}</a
				>
			{/each}
		</div>
	</div>

	{#if mobileMenuOpen}
		<div class="space-y-2 border-t border-primary px-6 pb-4 md:hidden">
			{#each navLinks as link}
				<a
					href={link.href}
					on:click={toggleMobileMenu}
					class="block pt-2 text-sm font-medium text-text-primary hover:text-text-secondary"
					>{link.text}</a
				>
			{/each}

			<div class="mt-4 border-t border-gray-200 pt-4">
				<a
					href="/auth/sign-in"
					class="block text-sm font-medium text-text-primary hover:text-text-secondary"
					>Sign-in</a
				>
				<a
					href="/auth/sign-up"
					class="mt-2 block w-full rounded bg-primary px-6 py-2 text-center text-sm font-medium text-white transition-colors hover:opacity-80"
					>Get Started</a
				>
			</div>
		</div>
	{/if}
</nav>

<style>
	.news-ticker {
		display: inline-block;
		white-space: nowrap;
		animation: ticker 40s linear infinite;
	}

	@keyframes ticker {
		0% {
			transform: translateX(0%);
		}
		100% {
			transform: translateX(-50%);
		}
	}
</style>
